### ISSUE TITLE
Le logo en haut à gauche est mal aligné

### ISSUE THREAD

**Issue by Morendil** [betagouv/blog.beta.gouv.fr#36]
La baseline horizontale de "blog" n'est pas alignée avec celle de "beta.gouv.fr".

**Comment by monbocal** [comment]
C'est un coup d'un margin-top à 1px à rajouter pour forcer un alignement visuel (les deux sont théoriquement strictement alignés).

Tu es sous quel navigateur pour vérifier que ce n'est pas plus grave ?

**Comment by Morendil** [comment]
Chrome 68

**Comment by monbocal** [comment]
OK, c'est donc ce soucis du pixel d'alignement. Je vais me motiver pour faire ça rapidement dans le CSS !

**Comment by monbocal** [comment]
Il y avait un conflit dans les CSS, un truc que je dois mieux réparer à l'avenir :) Quelle est ton impression maintenant sur l'alignement ?

**Comment by Morendil** [comment]
Hélas, sous Chrome 69:
![screen shot 2018-10-16 at 14 06 01](https://user-images.githubusercontent.com/216452/47015217-ae7dcd80-d14c-11e8-9bf2-8da899e15359.png)

**Comment by thimy** [comment]
Je m'en occupe ce soir ou demain, désolée.

**Comment by thimy** [comment]
La dernière version de https://rubygems.org/gems/jekyll-theme-gouvfr devrait réparer le logo !

**Comment by monbocal** [comment]
La modification du CSS avec `.navbar__gouvfr: height: 100%;` casse tout. J'ai repassé à `20px` en attendant de trouver où j'ai fait bêtise en mettant à jour le css.
![fail](https://user-images.githubusercontent.com/25476945/47096750-25d85d80-d230-11e8-8d1f-2060180d7fa3.png)

**Comment by thimy** [comment]
J'avais modifié les svg dans la foulée, j'ai l'impression que ça n'a pas été embarqué dans la PR 🤔

**Comment by monbocal** [comment]
C'était ça, j'avais mal fait la PR... mais par contre ça a bousillé l'alignement sous chrome /cry

**Comment by thimy** [comment]
Ça me parait plutôt ok de mon côté !

![image](https://user-images.githubusercontent.com/1301085/47100217-4eb02100-d237-11e8-8444-74514b2bbf1b.png)

**Comment by monbocal** [comment]
Sous windows Chrome j'ai ça . Ca s'aligne à nouveau en passant à 0 le padding-after :

![windowsalign](https://user-images.githubusercontent.com/25476945/47100378-9e8ee800-d237-11e8-837e-9d49ab9d4293.png)

**Comment by thimy** [comment]
Argh ! Sinon on passe le logo dynamique à la trappe et je te refais un logo tout neuf 😄

**Comment by Morendil** [comment]
#wontfix
