### ISSUE TITLE
Améliorer la sanitation des noms de RIBs

### ISSUE THREAD

**Issue by JeSuisUnCaillou** [betagouv/blog.beta.gouv.fr#365]
Lorsque les utilisateurs saisissent un nom de RIB, ils copient collent parfois des caractères étranges.
On les retire au moment de créer le fichier XML qui sera envoyé à l'ASP, car ils ont une liste assez stricte de ce qui peut être envoyé.

Tout se passe ici : https://github.com/betagouv/aplypro/blob/main/app/services/asp/mappers/coord_paie_mapper.rb

Lorsqu'un crée un fichier XML pour l'ASP avec un mauvais caractère dans le RIB, on obtient l'erreur de cette ligne : https://github.com/betagouv/aplypro/blob/main/app/services/asp/mappers/coord_paie_mapper.rb/#L49
Et ça empêche la création complète du fichier XML (bloquant donc 7000 payments)

**Comment by JeSuisUnCaillou** [comment]
Au lieu de lever une erreur, il faudrait que la sanitation s'assure vraiment qu'on bien ait que les caractères autorisés avec un whitelist.

**Comment by freesteph** [comment]
La seule subtilité qui empêche de faire un simple bitmask avec une liste de caractères autorisés c'est que certains doivent être remplacés par un espace et d'autre sans espaces : 

https://github.com/betagouv/aplypro/blob/93ab402950ad97b5412f07688f8164870dd79bec/app/services/asp/mappers/coord_paie_mapper.rb#L14-L15
