### ISSUE TITLE
Compatibilité Safari, Firefox

### ISSUE THREAD

**Issue by monbocal** [betagouv/blog.beta.gouv.fr#8]
Le CMS ne passe pas sous Safari (Mac OS), à regarder pourquoi

**Comment by monbocal** [comment]
Sous Firefox le formulaire de github déconne également

**Comment by monbocal** [comment]
Pour Safari, le problème est dans les issues du projet NetlifyCMS

**Comment by Morendil** [comment]
#wontfix
