### ISSUE TITLE
Problème de synchronisation du dossier _authors avec le repo beta.gouv.fr ?

### ISSUE THREAD

**Issue by IshanB** [betagouv/blog.beta.gouv.fr#98]
![image](https://user-images.githubusercontent.com/28890473/69067775-fa700580-0a23-11ea-9f79-784dbe8a7194.png)
Le rôle affiché n'est pas celui qui est indiqué sur la page authors du repo du site beta.gouv.fr
(https://github.com/betagouv/beta.gouv.fr/blob/master/content/_authors/ishan.bhojwani.md)

Est-ce un pb de synchronisation entre le dossier _authors du repo blog.beta.gouv.fr VS le même dossier dans le repo beta.gouv.fr ?

**Comment by Morendil** [comment]
😬 …je crois que la "synchronisation" en question se fait à la main. Elle n'a pas été faite depuis un bon bout de temps… genre mai 2019 (avec des mises à jours très partielles et ponctuelles entre-temps).

Je prends pour remettre les choses en ordre mais ce n'est clairement pas une solution pérenne. :)

**Comment by Morendil** [comment]
Je pense réintégrer le blog dans le site beta.gouv.fr, je ferme cette issue qui a trouvé une solution temporaire satisfaisante.
